#!/usr/bin/env python3

import os
import shutil
import hashlib
import time
import re
import itertools
import threading
import sys
import ssl
import urllib.request
from urllib.error import HTTPError, URLError
from urllib.parse import urlparse
from platform import python_version

################################################################
#
# Generated by: NCAR Climate Data Gateway
# Created: 2024-03-11T22:03:55-06:00
#
# Your download selection includes data that might be secured using API Token based
# authentication. Therefore, this script can have your api-token. If you
# re-generate your API Token after you download this script, the download will
# fail. If that happens, you can either re-download the script or you can edit
# this script replacing the old API Token with the new one. View your API token
# by going to "Account Home":
#
# https://www.earthsystemgrid.org/account/user/account-home.html
#
# and clicking on the "API Token" link under "Personal Account". You will be asked
# to log into the application before you can view your API Token.
#
# Usage: python3 python-ucar.cgd.cesm2le.atm.proc.monthly_ave.WSPDSRFAV-20240311T2203.py
# Version: 1.0.1
#
# Dataset
# ucar.cgd.cesm2le.atm.proc.monthly_ave.WSPDSRFAV
# 442f72c5-c347-4496-a490-f650ff6eba1b
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.atm.proc.monthly_ave.WSPDSRFAV.html
# https://www.earthsystemgrid.org/dataset/id/442f72c5-c347-4496-a490-f650ff6eba1b.html
#
# Dataset Version
# 2
# bda01a38-d22c-4b40-b106-687d066a072d
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.atm.proc.monthly_ave.WSPDSRFAV/version/2.html
# https://www.earthsystemgrid.org/dataset/version/id/bda01a38-d22c-4b40-b106-687d066a072d.html
#
################################################################

print('Please email feedback to esg-support@earthsystemgrid.org.\n')

data = [
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.001.cam.h0.WSPDSRFAV.197001-197912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.001.cam.h0.WSPDSRFAV.197001-197912.nc','bytes':'19477187','md5Checksum':'dce0b59f94e7746c17faf5c147281b9b'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.001.cam.h0.WSPDSRFAV.198001-198912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.001.cam.h0.WSPDSRFAV.198001-198912.nc','bytes':'19473015','md5Checksum':'687e30ab6d8d499425e28750f2d31923'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.001.cam.h0.WSPDSRFAV.199001-199912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.001.cam.h0.WSPDSRFAV.199001-199912.nc','bytes':'19468928','md5Checksum':'1f6fc0ea04ff225747bfa0e1d1a3da36'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.001.cam.h0.WSPDSRFAV.200001-200912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.001.cam.h0.WSPDSRFAV.200001-200912.nc','bytes':'19465026','md5Checksum':'aaefe942522cb837e75416233c477e5f'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.001.cam.h0.WSPDSRFAV.201001-201412.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.001.cam.h0.WSPDSRFAV.201001-201412.nc','bytes':'9771423','md5Checksum':'2ab4aacc3c38c3eaf2fa5726b6319bef'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.002.cam.h0.WSPDSRFAV.197001-197912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.002.cam.h0.WSPDSRFAV.197001-197912.nc','bytes':'19470970','md5Checksum':'9baac523a48770feb95b6afa90e90fe0'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.002.cam.h0.WSPDSRFAV.198001-198912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.002.cam.h0.WSPDSRFAV.198001-198912.nc','bytes':'19472382','md5Checksum':'d950add9917b23a17f979b4e3be3f739'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.002.cam.h0.WSPDSRFAV.199001-199912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.002.cam.h0.WSPDSRFAV.199001-199912.nc','bytes':'19468740','md5Checksum':'31e319b2ee4791b5529f99bc6eaba614'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.002.cam.h0.WSPDSRFAV.200001-200912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.002.cam.h0.WSPDSRFAV.200001-200912.nc','bytes':'19469709','md5Checksum':'2bf473e45aff571064a918e9dc0008aa'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.002.cam.h0.WSPDSRFAV.201001-201412.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.002.cam.h0.WSPDSRFAV.201001-201412.nc','bytes':'9770400','md5Checksum':'c6e03e17933d115d67f550338fedea3e'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.003.cam.h0.WSPDSRFAV.197001-197912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.003.cam.h0.WSPDSRFAV.197001-197912.nc','bytes':'19466643','md5Checksum':'b17418d78463e294919c8b49efb96513'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.003.cam.h0.WSPDSRFAV.198001-198912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.003.cam.h0.WSPDSRFAV.198001-198912.nc','bytes':'19477606','md5Checksum':'b929f142d787d1c8db75ea8d927fcbcd'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.003.cam.h0.WSPDSRFAV.199001-199912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.003.cam.h0.WSPDSRFAV.199001-199912.nc','bytes':'19463798','md5Checksum':'3bb88c50f8b2a1c7ec74c39e58c61c52'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.003.cam.h0.WSPDSRFAV.200001-200912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.003.cam.h0.WSPDSRFAV.200001-200912.nc','bytes':'19464152','md5Checksum':'5bef9ee5e8150a51e074fd4aee3398d7'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.003.cam.h0.WSPDSRFAV.201001-201412.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.003.cam.h0.WSPDSRFAV.201001-201412.nc','bytes':'9775982','md5Checksum':'d5dd70bb5b349be8c7ee0a4b8e09b12d'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.004.cam.h0.WSPDSRFAV.197001-197912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.004.cam.h0.WSPDSRFAV.197001-197912.nc','bytes':'19628842','md5Checksum':'33542893fad08608e073984aae973fe2'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.004.cam.h0.WSPDSRFAV.198001-198912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.004.cam.h0.WSPDSRFAV.198001-198912.nc','bytes':'19619490','md5Checksum':'9c75974cd18add8f1a1ecd12a7655dcc'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.004.cam.h0.WSPDSRFAV.199001-199912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.004.cam.h0.WSPDSRFAV.199001-199912.nc','bytes':'19621046','md5Checksum':'66f807bc6f8b95b5b9bca25f4c38d7b1'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.004.cam.h0.WSPDSRFAV.200001-200912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.004.cam.h0.WSPDSRFAV.200001-200912.nc','bytes':'19616772','md5Checksum':'669fd3984a830b3a2b9ce44eba626a22'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.004.cam.h0.WSPDSRFAV.201001-201412.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.004.cam.h0.WSPDSRFAV.201001-201412.nc','bytes':'9847377','md5Checksum':'e666f0b5e9771263962bab8f81397b80'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.005.cam.h0.WSPDSRFAV.197001-197912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.005.cam.h0.WSPDSRFAV.197001-197912.nc','bytes':'19478042','md5Checksum':'3bae29e760f6d17856e524e57f8aa0d8'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.005.cam.h0.WSPDSRFAV.198001-198912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.005.cam.h0.WSPDSRFAV.198001-198912.nc','bytes':'19474817','md5Checksum':'c5806ac07015824ec4daa195bdb3c6fc'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.005.cam.h0.WSPDSRFAV.199001-199912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.005.cam.h0.WSPDSRFAV.199001-199912.nc','bytes':'19465560','md5Checksum':'0293bd78ab686f928d0896f8357736c9'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.005.cam.h0.WSPDSRFAV.200001-200912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.005.cam.h0.WSPDSRFAV.200001-200912.nc','bytes':'19466428','md5Checksum':'7a86e13be8e610c5afac0af9252a6267'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.005.cam.h0.WSPDSRFAV.201001-201412.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.005.cam.h0.WSPDSRFAV.201001-201412.nc','bytes':'9772284','md5Checksum':'33e87c493c0a8283fff345c5b1373bbf'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.006.cam.h0.WSPDSRFAV.197001-197912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.006.cam.h0.WSPDSRFAV.197001-197912.nc','bytes':'19472478','md5Checksum':'133591528b7596b4db6140c074d0dee8'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.006.cam.h0.WSPDSRFAV.198001-198912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.006.cam.h0.WSPDSRFAV.198001-198912.nc','bytes':'19476386','md5Checksum':'1cf4c61381ac22c5430abbc30cc51d0a'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.006.cam.h0.WSPDSRFAV.199001-199912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.006.cam.h0.WSPDSRFAV.199001-199912.nc','bytes':'19468483','md5Checksum':'2e85ef3e1fccccce3336b0484240fab4'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.006.cam.h0.WSPDSRFAV.200001-200912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.006.cam.h0.WSPDSRFAV.200001-200912.nc','bytes':'19468447','md5Checksum':'89f22d27f749de47973e040900f6d84e'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.006.cam.h0.WSPDSRFAV.201001-201412.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.006.cam.h0.WSPDSRFAV.201001-201412.nc','bytes':'9772672','md5Checksum':'40f6854ad2171fa366fd536473f53ac4'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.007.cam.h0.WSPDSRFAV.197001-197912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.007.cam.h0.WSPDSRFAV.197001-197912.nc','bytes':'19472860','md5Checksum':'4d758f251dd58269e7056d74a77e1059'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.007.cam.h0.WSPDSRFAV.198001-198912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.007.cam.h0.WSPDSRFAV.198001-198912.nc','bytes':'19472486','md5Checksum':'88174f2bbe0d205772fd645786dd2111'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.007.cam.h0.WSPDSRFAV.199001-199912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.007.cam.h0.WSPDSRFAV.199001-199912.nc','bytes':'19467673','md5Checksum':'dc36323965d6000ee8bc3ccead6a7bcb'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.007.cam.h0.WSPDSRFAV.200001-200912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.007.cam.h0.WSPDSRFAV.200001-200912.nc','bytes':'19470567','md5Checksum':'790ae271df6b719fb7375199e9a1f41d'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.007.cam.h0.WSPDSRFAV.201001-201412.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.007.cam.h0.WSPDSRFAV.201001-201412.nc','bytes':'9773812','md5Checksum':'26ea5246b2daec6ac6ebe38cfefefca1'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.008.cam.h0.WSPDSRFAV.197001-197912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.008.cam.h0.WSPDSRFAV.197001-197912.nc','bytes':'19469031','md5Checksum':'54d6a996c98aa937071efa96dc545a7c'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.008.cam.h0.WSPDSRFAV.198001-198912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.008.cam.h0.WSPDSRFAV.198001-198912.nc','bytes':'19480172','md5Checksum':'74f5ee78dcc7dee598d9d83b67ee87a3'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.008.cam.h0.WSPDSRFAV.199001-199912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.008.cam.h0.WSPDSRFAV.199001-199912.nc','bytes':'19472229','md5Checksum':'ac6e2f061a25e79a0ae7f2a7fe85be6e'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.008.cam.h0.WSPDSRFAV.200001-200912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.008.cam.h0.WSPDSRFAV.200001-200912.nc','bytes':'19458420','md5Checksum':'f3e953c8818c4670a2fce00898809dae'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.008.cam.h0.WSPDSRFAV.201001-201412.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.008.cam.h0.WSPDSRFAV.201001-201412.nc','bytes':'9771663','md5Checksum':'2a15d9437c82842f0a5e5aa6da372ebe'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.009.cam.h0.WSPDSRFAV.197001-197912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.009.cam.h0.WSPDSRFAV.197001-197912.nc','bytes':'19471701','md5Checksum':'65199c8d0c91ad4ca2c9684174641727'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.009.cam.h0.WSPDSRFAV.198001-198912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.009.cam.h0.WSPDSRFAV.198001-198912.nc','bytes':'19471378','md5Checksum':'d870a50ca31a236c72947c1eb4287ac6'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.009.cam.h0.WSPDSRFAV.199001-199912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.009.cam.h0.WSPDSRFAV.199001-199912.nc','bytes':'19472338','md5Checksum':'2b11f3921868ea6c8c86ce1347792ec2'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.009.cam.h0.WSPDSRFAV.200001-200912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.009.cam.h0.WSPDSRFAV.200001-200912.nc','bytes':'19474575','md5Checksum':'111ba1942651a5e59940b860de7a7ef0'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.009.cam.h0.WSPDSRFAV.201001-201412.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.009.cam.h0.WSPDSRFAV.201001-201412.nc','bytes':'9775088','md5Checksum':'49f7d6af14eb20c234ba905d28adcdc8'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.010.cam.h0.WSPDSRFAV.197001-197912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.010.cam.h0.WSPDSRFAV.197001-197912.nc','bytes':'19478642','md5Checksum':'6fe08283c10d9a8261984bf429c8b343'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.010.cam.h0.WSPDSRFAV.198001-198912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.010.cam.h0.WSPDSRFAV.198001-198912.nc','bytes':'19473873','md5Checksum':'8258b266fca3265d90ba8994a30973b6'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.010.cam.h0.WSPDSRFAV.199001-199912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.010.cam.h0.WSPDSRFAV.199001-199912.nc','bytes':'19469446','md5Checksum':'db4720644b61c56c1d46bed3b7f0ddf7'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.010.cam.h0.WSPDSRFAV.200001-200912.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.010.cam.h0.WSPDSRFAV.200001-200912.nc','bytes':'19470555','md5Checksum':'dc751f765500b9baa0ae51ab5712f943'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BHISTcmip6.f09_g17.LE2-1231.010.cam.h0.WSPDSRFAV.201001-201412.nc','filename':'b.e21.BHISTcmip6.f09_g17.LE2-1231.010.cam.h0.WSPDSRFAV.201001-201412.nc','bytes':'9772940','md5Checksum':'f5f62e20a505fe28271df5dae9107269'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.001.cam.h0.WSPDSRFAV.202501-203412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.001.cam.h0.WSPDSRFAV.202501-203412.nc','bytes':'19462509','md5Checksum':'27dc3b8bccaa0ec567e937dd9878cd8a'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.001.cam.h0.WSPDSRFAV.203501-204412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.001.cam.h0.WSPDSRFAV.203501-204412.nc','bytes':'19455849','md5Checksum':'0f3335b7ef0aaa390e426f651db8d150'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.001.cam.h0.WSPDSRFAV.204501-205412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.001.cam.h0.WSPDSRFAV.204501-205412.nc','bytes':'19463321','md5Checksum':'be9436f6297a60f61998674cb50664e4'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.001.cam.h0.WSPDSRFAV.205501-206412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.001.cam.h0.WSPDSRFAV.205501-206412.nc','bytes':'19445746','md5Checksum':'a94103a7c99d2ef5af10e95460374fea'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.002.cam.h0.WSPDSRFAV.202501-203412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.002.cam.h0.WSPDSRFAV.202501-203412.nc','bytes':'19454761','md5Checksum':'7923dbe1e649d0aeb4e3e4d0f7257d87'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.002.cam.h0.WSPDSRFAV.203501-204412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.002.cam.h0.WSPDSRFAV.203501-204412.nc','bytes':'19457855','md5Checksum':'1767d0eb8524c4caba9151a2556b038a'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.002.cam.h0.WSPDSRFAV.204501-205412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.002.cam.h0.WSPDSRFAV.204501-205412.nc','bytes':'19453821','md5Checksum':'e0b30195b6887ef76be68e3abb5da66e'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.002.cam.h0.WSPDSRFAV.205501-206412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.002.cam.h0.WSPDSRFAV.205501-206412.nc','bytes':'19457987','md5Checksum':'491b011a7ebfe36e624402f9c0cc10e9'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.003.cam.h0.WSPDSRFAV.202501-203412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.003.cam.h0.WSPDSRFAV.202501-203412.nc','bytes':'19465809','md5Checksum':'0f9311686009146c776a789392f3c9c8'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.003.cam.h0.WSPDSRFAV.203501-204412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.003.cam.h0.WSPDSRFAV.203501-204412.nc','bytes':'19460296','md5Checksum':'14a6fe4a41145110f308714d569eba43'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.003.cam.h0.WSPDSRFAV.204501-205412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.003.cam.h0.WSPDSRFAV.204501-205412.nc','bytes':'19457661','md5Checksum':'dea0cd3bbf42194d3f89ca4ceeb2ec40'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.003.cam.h0.WSPDSRFAV.205501-206412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.003.cam.h0.WSPDSRFAV.205501-206412.nc','bytes':'19457357','md5Checksum':'cfdf3ab2a45dc3a6391bd123dc73dd4d'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.004.cam.h0.WSPDSRFAV.202501-203412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.004.cam.h0.WSPDSRFAV.202501-203412.nc','bytes':'19464654','md5Checksum':'e607481c8cd8568c8175c0883b35f84d'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.004.cam.h0.WSPDSRFAV.203501-204412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.004.cam.h0.WSPDSRFAV.203501-204412.nc','bytes':'19451710','md5Checksum':'febcbde17f0937655f9eb6378618e3d0'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.004.cam.h0.WSPDSRFAV.204501-205412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.004.cam.h0.WSPDSRFAV.204501-205412.nc','bytes':'19458151','md5Checksum':'8856b40458bada5c0a83e855f8d64619'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.004.cam.h0.WSPDSRFAV.205501-206412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.004.cam.h0.WSPDSRFAV.205501-206412.nc','bytes':'19456841','md5Checksum':'adf4cb576f7b9859e0b56807660f3963'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.005.cam.h0.WSPDSRFAV.202501-203412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.005.cam.h0.WSPDSRFAV.202501-203412.nc','bytes':'19459640','md5Checksum':'ca1f4d2e81df706cd28b4cdf3d88021a'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.005.cam.h0.WSPDSRFAV.203501-204412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.005.cam.h0.WSPDSRFAV.203501-204412.nc','bytes':'19463537','md5Checksum':'090c2d547c47bd0e1c70643d46596958'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.005.cam.h0.WSPDSRFAV.204501-205412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.005.cam.h0.WSPDSRFAV.204501-205412.nc','bytes':'19449324','md5Checksum':'67781e9d5a72c71b76a2f531b464def6'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.005.cam.h0.WSPDSRFAV.205501-206412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.005.cam.h0.WSPDSRFAV.205501-206412.nc','bytes':'19448933','md5Checksum':'2d8f76c71d99fd94082433d2f65aa101'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.006.cam.h0.WSPDSRFAV.202501-203412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.006.cam.h0.WSPDSRFAV.202501-203412.nc','bytes':'19612134','md5Checksum':'e0921eaac08f46a53e96634ef628d78e'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.006.cam.h0.WSPDSRFAV.203501-204412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.006.cam.h0.WSPDSRFAV.203501-204412.nc','bytes':'19611355','md5Checksum':'e6cae026f3022153303583f10bb9a765'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.006.cam.h0.WSPDSRFAV.204501-205412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.006.cam.h0.WSPDSRFAV.204501-205412.nc','bytes':'19597968','md5Checksum':'4484fac15990b77b87749722d0484394'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.006.cam.h0.WSPDSRFAV.205501-206412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.006.cam.h0.WSPDSRFAV.205501-206412.nc','bytes':'19599343','md5Checksum':'7993edd77dff4c4ba0c8c34de5b416df'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.007.cam.h0.WSPDSRFAV.202501-203412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.007.cam.h0.WSPDSRFAV.202501-203412.nc','bytes':'19458292','md5Checksum':'2cb3b7b3a58f5743b8a29026e326eba6'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.007.cam.h0.WSPDSRFAV.203501-204412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.007.cam.h0.WSPDSRFAV.203501-204412.nc','bytes':'19457943','md5Checksum':'59c9e4553a35a441a906c63d7f2b9c30'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.007.cam.h0.WSPDSRFAV.204501-205412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.007.cam.h0.WSPDSRFAV.204501-205412.nc','bytes':'19452200','md5Checksum':'6bd6c9d56cf5387de3a9ad96cfc9fbb2'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.007.cam.h0.WSPDSRFAV.205501-206412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.007.cam.h0.WSPDSRFAV.205501-206412.nc','bytes':'19460977','md5Checksum':'68651e98a08e787df663efeff98580f7'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.008.cam.h0.WSPDSRFAV.202501-203412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.008.cam.h0.WSPDSRFAV.202501-203412.nc','bytes':'19462206','md5Checksum':'5ec5af0813c2b747c1b12f1c5b53e9cf'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.008.cam.h0.WSPDSRFAV.203501-204412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.008.cam.h0.WSPDSRFAV.203501-204412.nc','bytes':'19457647','md5Checksum':'ecf411f530f3a42e17ba0d14d68bf6d6'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.008.cam.h0.WSPDSRFAV.204501-205412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.008.cam.h0.WSPDSRFAV.204501-205412.nc','bytes':'19459997','md5Checksum':'a69517aa9ddb169807b77bdd4427f335'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.008.cam.h0.WSPDSRFAV.205501-206412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.008.cam.h0.WSPDSRFAV.205501-206412.nc','bytes':'19451978','md5Checksum':'a2ab8e0fcda8c8716984c528c63ab39e'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.009.cam.h0.WSPDSRFAV.202501-203412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.009.cam.h0.WSPDSRFAV.202501-203412.nc','bytes':'19470502','md5Checksum':'3975fc7071b33b481ad1d1b2b14026e4'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.009.cam.h0.WSPDSRFAV.203501-204412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.009.cam.h0.WSPDSRFAV.203501-204412.nc','bytes':'19457838','md5Checksum':'0c5d294f5ff342529b2dd59e0277b127'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.009.cam.h0.WSPDSRFAV.204501-205412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.009.cam.h0.WSPDSRFAV.204501-205412.nc','bytes':'19453509','md5Checksum':'cd117bb8039e438d491eb84fec2e185a'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.009.cam.h0.WSPDSRFAV.205501-206412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.009.cam.h0.WSPDSRFAV.205501-206412.nc','bytes':'19451556','md5Checksum':'ecd16b13a3c61992e7b40e127921c8e2'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.010.cam.h0.WSPDSRFAV.202501-203412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.010.cam.h0.WSPDSRFAV.202501-203412.nc','bytes':'19616507','md5Checksum':'9e4996a4e59bb49339ab0dfb69a6e455'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.010.cam.h0.WSPDSRFAV.203501-204412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.010.cam.h0.WSPDSRFAV.203501-204412.nc','bytes':'19609096','md5Checksum':'893bf7302a2107bd977db99506b4e44f'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.010.cam.h0.WSPDSRFAV.204501-205412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.010.cam.h0.WSPDSRFAV.204501-205412.nc','bytes':'19606089','md5Checksum':'5dbf9969cb8b8ff2110522dbad909e0c'},
     {'url':'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/atm/proc/tseries/month_1/WSPDSRFAV/b.e21.BSSP370cmip6.f09_g17.LE2-1231.010.cam.h0.WSPDSRFAV.205501-206412.nc','filename':'b.e21.BSSP370cmip6.f09_g17.LE2-1231.010.cam.h0.WSPDSRFAV.205501-206412.nc','bytes':'19604973','md5Checksum':'e89372dbee1475f3f1ab79784a214fb0'},]

def main(data):

    args = processArguments()

    for d in data:
        executeDownload(Download(args, d))

def processArguments():

    args = {}
    args.update({'apiToken': '6gVAiOJqI4I3oNMuiEstMigjNakfq62LZRHVcwJ0'})
    args.update({'userAgent': 'python/{}/gateway/{}'.format(python_version(), '4.4.4-20240220-190232')})
    args.update({'attemptMax': 10})
    args.update({'initialSleepSeconds': 10})
    args.update({'sleepMultiplier': 3})
    args.update({'sleepMaxSeconds': 900})
    args.update({'insecure': False})

    if '-k' in sys.argv or '--insecure' in sys.argv:
        args.update({'insecure': True})

    if '-h' in sys.argv or '--help' in sys.argv:
        print('Usage: {} [options...]'.format(sys.argv[0]))
        print(' -h, --help        Show usage')
        print(' -k, --insecure    Allow insecure server connections (no certificate check) when using SSL')
        exit(0)

    return args

def executeDownload(download):

    if not os.path.isfile(download.filename):
        attemptAndValidateDownload(download)
        moveDownload(download)
    else:
        download.success = True
        download.valid = True

    reportDownload(download)

def moveDownload(download):

    if download.success and (download.valid or download.vwarning):
        os.rename(download.filenamePart, download.filename)

def reportDownload(download):

    if download.success and download.valid:
        print('{} download successful'.format(download.filename))

    if download.success and not download.valid and download.vwarning:
        print('{} download validation warning: {}'.format(download.filename, download.vwarning))

    if download.success and not download.valid and download.verror:
        print('{} download validation error: {}'.format(download.filename, download.verror))

    if not download.success and download.error:
        print('{} download failed: {}'.format(download.filename, download.error))

def attemptAndValidateDownload(download):

    while download.attempt:
        downloadFile(download)

    if download.success:
        validateFile(download)

def downloadFile(download):

    try :
        startOrResumeDownload(download)
    except HTTPError as error:
        handleHTTPErrorAttempt(download, error)
    except URLError as error:
        handleRecoverableAttempt(download, error)
    except TimeoutError as error:
        handleRecoverableAttempt(download, error)
    except Exception as error:
        handleIrrecoverableAttempt(download, error)
    else:
        handleSuccessfulAttempt(download)

def startOrResumeDownload(download):

    startAnimateDownload('{} downloading:'.format(download.filename))

    if os.path.isfile(download.filenamePart):
        resumeDownloadFile(download)
    else:
        startDownloadFile(download)

def startAnimateDownload(message):
    global animateMessage
    global animateOn

    animateMessage = message
    animateOn = True

    # making the animation run as a daemon thread allows it to
    # exit when the parent (main) is terminated or killed
    t = threading.Thread(daemon=True, target=animateDownload)
    t.start()

def stopAnimateDownload(outcome):
    global animateOutcome
    global animateOn

    animateOutcome = outcome
    animateOn = False

    # wait for animation child process to stop before any parent print
    time.sleep(0.3)

def animateDownload():
    global animateMessage
    global animateOutcome
    global animateOn

    for d in itertools.cycle(['.  ', '.. ', '...', '   ']):

        if not animateOn:
            print('\r{} {}'.format(animateMessage, animateOutcome), flush=True)
            break

        print('\r{} {}'.format(animateMessage, d), end='', flush=True)
        time.sleep(0.2)

def resumeDownloadFile(download):

    request = createRequest(download, createResumeHeaders(download))
    readFile(download, request)

def startDownloadFile(download):

    request = createRequest(download, createStartHeaders(download))
    readFile(download, request)

def createResumeHeaders(download):

    headers = createStartHeaders(download)
    headers.update(createRangeHeader(download))

    return headers

def createRequest(download, headers):

    request = urllib.request.Request(download.url, headers=headers)

    return request

def createStartHeaders(download):

    headers = {}
    headers.update(createUserAgentHeader(download))

    if download.apiToken:
        headers.update(createAuthorizationHeader(download))

    return headers

def createUserAgentHeader(download):

    return {'User-agent': download.userAgent}

def createAuthorizationHeader(download):

    return {'Authorization': 'api-token {}'.format(download.apiToken)}

def createRangeHeader(download):

    start = os.path.getsize(download.filenamePart)
    header = {'Range': 'bytes={}-'.format(start)}

    return header

def readFile(download, request):

    context = createSSLContext(download)

    with urllib.request.urlopen(request, context=context) as response, open(download.filenamePart, 'ab') as fh:
        collectResponseHeaders(download, response)
        shutil.copyfileobj(response, fh)

def createSSLContext(download):

    # See:
    #      https://docs.python.org/3/library/urllib.request.html
    #      https://docs.python.org/3/library/http.client.html#http.client.HTTPSConnection
    #      https://docs.python.org/3/library/ssl.html#ssl.SSLContext
    #
    # Excerpts:
    #      If context is specified it must be a ssl.SSLContext instance...
    #      http.client.HTTPSConnection performs all the necessary certificate and hostname checks by default.

    if download.insecure:
        return ssl._create_unverified_context()

    return None

def collectResponseHeaders(download, response):

    download.responseHeaders = response.info()
    if download.responseHeaders.get('ETag'):
        download.etag = download.responseHeaders.get('ETag').strip('"')

def handleHTTPErrorAttempt(download, httpError):

    if httpError.code == 416: # 416 is Range Not Satisfiable
        # likely the file completely downloaded and validation was interrupted,
        # therefore calling it successfully downloaded and allowing validation
        # to say otherwise
        handleSuccessfulAttempt(download)
    else:
        handleRecoverableAttempt(download, httpError)

def handleRecoverableAttempt(download, error):

    stopAnimateDownload('error')

    print('failure on attempt {} downloading {}: {}'.format(download.attemptNumber, download.filename, error))

    if download.attemptNumber < download.attemptMax:
        sleepBeforeNextAttempt(download)
        download.attemptNumber += 1
    else:
        download.attempt = False
        download.error = error

def sleepBeforeNextAttempt(download):

    sleepSeconds = download.initialSleepSeconds * (download.sleepMultiplier ** (download.attemptNumber - 1))

    if sleepSeconds > download.sleepMaxSeconds:
        sleepSeconds = download.sleepMaxSeconds

    print('waiting {} seconds before next attempt to download {}'.format(sleepSeconds, download.filename))
    time.sleep(sleepSeconds)

def handleIrrecoverableAttempt(download, error):

    stopAnimateDownload('error')

    download.attempt = False
    download.error = error

def handleSuccessfulAttempt(download):

    stopAnimateDownload('done')

    download.attempt = False
    download.success = True

def validateFile(download):

    try:
        validateAllSteps(download)
    except InvalidDownload as error:
        download.valid = False
        download.vwarning = str(error)
    except Exception as error:
        download.valid = False
        download.verror = error
    else:
        download.valid = True

def validateAllSteps(download):

    verrorData = validatePerData(download)
    verrorEtag = validatePerEtag(download)
    verrorStale = validateStaleness(download)

    if verrorData and verrorEtag:
        raise verrorData

    if verrorStale:
        raise verrorStale

def validatePerData(download):

    try:
        validateBytes(download)
        validateChecksum(download)
    except InvalidDownload as error:
        return error
    else:
        return None

def validateBytes(download):

    size = os.path.getsize(download.filenamePart)
    if not download.bytes == size:
        raise InvalidSizeValue(download, size)

def validateChecksum(download):

    if download.md5Checksum:
        md5Checksum = readMd5Checksum(download)
        if not download.md5Checksum == md5Checksum:
            raise InvalidChecksumValue(download, md5Checksum)
    else:
        raise UnableToPerformChecksum(download)

def readMd5Checksum(download):

    hash_md5 = hashlib.md5()

    with open(download.filenamePart, 'rb') as f:
        for chunk in iter(lambda: f.read(4096), b''):
            hash_md5.update(chunk)

    return hash_md5.hexdigest()

def validatePerEtag(download):

    try:
        validateChecksumEtag(download)
    except InvalidDownload as error:
        return error
    else:
        return None

def validateChecksumEtag(download):

    if isEtagChecksum(download):
        md5Checksum = readMd5Checksum(download)
        if not download.etag == md5Checksum:
            raise InvalidChecksumValuePerEtag(download, md5Checksum)
    else:
        raise UnableToPerformChecksum(download)

def isEtagChecksum(download):

    return download.etag and re.fullmatch(r'[a-z0-9]+', download.etag)

def validateStaleness(download):

    try:
        validateStaleChecksum(download)
    except InvalidDownload as error:
        return error
    else:
        return None

def validateStaleChecksum(download):

    if isEtagChecksum(download):
        if not download.md5Checksum or download.md5Checksum != download.etag:
            raise StaleChecksumValue(download)

class InvalidDownload(Exception):

    pass

class InvalidSizeValue(InvalidDownload):

    def __init__(self, download, actual):
        super().__init__('invalid byte size for {}: downloaded file is {} bytes but should be {}'.format(download.filename, actual, download.bytes))

class InvalidChecksumValue(InvalidDownload):

    def __init__(self, download, actual):
        super().__init__('invalid checksum for {}: downloaded file is {} but should be {}'.format(download.filename, actual, download.md5Checksum))

class InvalidChecksumValuePerEtag(InvalidDownload):

    def __init__(self, download, actual):
        super().__init__('invalid checksum for {}: downloaded file is {} but should be {} according to server'.format(download.filename, actual, download.etag))

class UnableToPerformChecksum(InvalidDownload):

    def __init__(self, download):
        super().__init__('cannot verify checksum of {}'.format(download.filename))

class StaleChecksumValue(InvalidDownload):

    def __init__(self, download):
        super().__init__('checksum value has changed for {}'.format(download.filename))

class Download():

    def __init__(self, args, datum):

        self.apiToken = args.get('apiToken')
        self.userAgent = args.get('userAgent')
        self.attemptMax = args.get('attemptMax')
        self.initialSleepSeconds = args.get('initialSleepSeconds')
        self.sleepMultiplier = args.get('sleepMultiplier')
        self.sleepMaxSeconds = args.get('sleepMaxSeconds')
        self.insecure = args.get('insecure')

        self.url = datum.get('url')
        self.filename = datum.get('filename')
        self.bytes = int(datum.get('bytes'))
        self.md5Checksum = datum.get('md5Checksum')

        self.filenamePart = self.filename + '.part'
        self.success = False
        self.attempt = True
        self.attemptNumber = 1
        self.responseHeaders = {}
        self.etag = None
        self.error = None
        self.valid = False
        self.vwarning = None
        self.verror = None

    def __str__(self):
        return f'url: {self.url}, filename: {self.filename}, bytes: {self.bytes}, md5Checksum: {self.md5Checksum}'

if __name__ == '__main__':
    main(data)
